trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Spring Boot App'
        steps:
          - task: Maven@3
            displayName: 'Maven Package'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package -DskipTests'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish JAR Artifact'
            inputs:
              PathtoPublish: 'target'
              ArtifactName: 'drop'
  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    jobs:
      - job: DeployJob
        displayName: 'Deploy to Azure App Service'
        steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureWebApp@1
            displayName: 'Deploy to App Service'
            inputs:
              azureSubscription: 'azure-connection'
              appType: 'webAppLinux'
              appName: 'sarthak-azure-demo-2026'
              package: '$(System.ArtifactsDirectory)/drop/*.jar'
              runtimeStack: 'JAVA|17-java17'
